id: P399B02BB
initial_creation_type: ocr
source_metadata:
  volumes:
    8c781fad0b414869b61b6ab7d9f64fbd:
      base_file: v052.txt
      image_group_id: I1PD95897
      title: བཅོམ་ལྡན་འདས་ཡོན་ཏན་རིན་པོ་ཆེ་སྡུད་པའི་ཚིགས་སུ་བཅད་པའི་དཀའ་འགྲེལ།
      total_pages: 1426
      volume_number: 52
